### ISSUE TITLE
Unexpected dropping and re-adding foreign keys in MySQL 5.7

### ISSUE THREAD

**Issue by kenkoooo** [k0kubun/sqldef#205]
Thank you for creating such a great tool!

Let me report an issue I found when I use `mysqldef v0.11.35` in MySQL 5.7. In MySQL 5.7, it drops foreign keys and adds them again even though the schema definition is not changed. It doesn't happen in MySQL 8.0.

## --export output
```sql
CREATE TABLE `groups` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `users` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `group_id` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_users_groups` (`group_id`),
  CONSTRAINT `fk_users_groups` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

## Input SQL
```sql
CREATE TABLE groups
(
    `id`         BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE users
(
    `id`           BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `group_id`     BIGINT       NOT NULL,
    KEY `fk_users_groups` (`group_id`),
    CONSTRAINT `fk_users_groups` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
);
```

## Current output
```
ALTER TABLE `users` DROP FOREIGN KEY `fk_users_groups`;
ALTER TABLE `users` ADD CONSTRAINT `fk_users_groups` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
```

## Expected output

It should be nothing.

## docker-compose.yml
```yml
version: "3.5"

services:
  mysql8:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
```
