### ISSUE TITLE
Cannot create policy after create table

### ISSUE THREAD

**Issue by tomocrafter** [k0kubun/sqldef#332]
## --export output
None

## Input SQL
Add following test to `cmd/psqldef/tests.yml`

```yaml
AddPolicy:
  current: |
    CREATE TABLE accounts (manager text, company text, contact_email text);
  desired: |
    CREATE POLICY account_managers ON accounts TO managers
      USING (manager = current_user);
```

## Current output
```
CREATE POLICY is performed before create table 'public.accounts': 'CREATE POLICY account_managers ON accounts TO managers
              USING (manager = current_user)'
```

## Expected output
Successfully policy created

because it is validatting current table *and* desired table not current table *or* desired table here:
https://github.com/k0kubun/sqldef/blob/master/schema/generator.go#L695
https://github.com/k0kubun/sqldef/blob/master/schema/generator.go#L714
